name: deploy to cloud
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.16.1]
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      - name: SSH Execute Commands
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: "root@${{ secrets.HOST }} -o StrictHostKeyChecking=no"
          privateKey: ${{ secrets.ACCESS_TOKEN }}
          debug: true
          command: |
            sh /data/source/build.sh
